# Live Code-Along: A Beginner's Guide to Data Analysis with SQL

## Key session takeaways

* Learn the basics of SQL & why it's foundational for data science work.
* Filter, group by, and analyse datasets using SQL.
* Answer key business questions with SQL

## The Dataset 

The dataset to be used in this training is a CSV file named `airbnb_data.csv`, which contains data on airbnb listings in the state of New York. It contains the following columns:

* `listing_id`: The unique identifier for a listing 
* `description`: The description used on the listing 
* `host_id`: Unique identifier for a host 
* `neighbourhood_full`: Name of boroughs and neighbourhoods 
* `coordinates`: Coordinates of listing (latitude, longitude) 
* `listing_added`: Date of added listing 
* `room_type`: Type of room 
* `rating`: Rating from 0 to 5. 
* `price`: Price per night for listing 
* `number_of_reviews`: Amount of reviews received 
* `reviews_per_month`: Number of reviews per month 
* `availability_365`: Number of days available per year 
* `number_of_stays`: Total number of stays thus far 

## Questions to answer 

* **Question 1**: List the top 10 most reviewed private rooms
* **Question 2**: What are the cheapest 10 private rooms in New York?
* **Question 3**: What is the average availability of a private room in New York?

**Q&A**

* **Question 4**: Which listings have an availability of fewer than 30 days a year but have fewer than 10 reviews?
* **Question 5**: What is the average number of reviews per room type, ordered by the average in descending order?
* **Question 6**: What is the number and average price of listings by room type where such listings are available for more than 250 days a year?

## Some SQL Basics 

### SQL Commands

Before we dive into answering our questions, let's get familiar with SQL syntax. Today, we'll be covering the most useful SQL commands â€” let's start with them one by one. This includes the following:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `LIMIT`: limits the number of rows returned.
* `AS`: lets you set an alias for a particular column 
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `WHERE`: lets you filter on a specific column or value
* `GROUP BY`: lets you aggregate on one or more columns 
* `MAX()`: returns the maximum amount of a particular column 
* `AVG()`: returns the total average of a particular column 

### Code Commenting
There are two types of code commenting in Postgres

-- `Inline commenting` : Used for quick, short notes 

"/*" `Multi line commenting` "*/" (use without quotation marks): Used for longer comments, such as metadata, or code headers including the author, date, purpose, etc.

### Let's Practice Some SQL!

In [1]:
-- SELECT the first 10 rows of all the columns from the airbnb dataset

In [5]:
-- SELECT the first 10 rows of the listing_id, description, and neighbourhood_full columns

In [6]:
-- Set an alias for listing_id, description and neighbourhood_full

In [14]:
-- Sort the output by number of stays

In [17]:
-- Filter room type by private room

In [10]:
-- Get the average price for all rooms

In [11]:
-- Get the average price per room type

# **Q&A**

## Let's answer some questions!

### Question 1: List the top 10 most reviewed private rooms

In order to answer this question, we need to filter on `room_type` and order by `reviews_per_month`, and limit to the top 10 results. Here are the commands we need to use:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `WHERE`: specifies a condition on a column
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `LIMIT`: returns the specified number of rows

In [18]:
-- List the top 10 most reviewed private rooms

## Question 2: What are the cheapest 10 private rooms in New York?

In order to answer this question, we need to filter on `room_type` and order by `price`, and limit to the top 10 results. Here are the commands we need to use:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `WHERE`: specifies a condition on a column
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `LIMIT`: returns the specified number of rows

In [19]:
-- List the top 10 cheapest private rooms in New York

## Question 3: What is the average availability of a private room in New York?

In order to answer this question, we need to filter on `room_type` and compute the average of `availability_365`. Here are the commands we need to use:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `WHERE`: specifies a condition on a column
* `AVG`: returns the average of a column

In [20]:
-- What is the average availability of a private room in New York?

# Q&A

## Question 4: Which listings have an availability of fewer than 30 days a year but have fewer than 10 reviews?

In order to answer this question, we need to filter both on availability and number of reviews. Here are the commands we will need:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `WHERE`: lets you filter on a specific column or value
* `AND`: lets you chain conditions

In [21]:
-- Which listings have an availability of fewer than 30 days a year but have fewer than 10 reviews?

## Question 5: What is the average number of reviews per room type, ordered by the average in descending order?

In order to answer this question, we need to filter both on availability and number of reviews. Here are the commands we will need:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `WHERE`: lets you filter on a specific column or value
* `AND`: lets you chain conditions

In [25]:
-- What is the average number of reviews per room type, ordered by the average in ascending order?

## Question 6: What is the number and average price of listings by room type where such listings are available for more than 250 days a year? 

In order to answer this question, we need to group by room type, compute the average of availability per year, and order by average availability. Here are the commands we will need:

* `SELECT`: returns either all columns using * or specific columns as specified, seperated by a comma. 
* `FROM` : specifies the table that the data should be returned from. 
* `AS`: lets you set an alias for a particular column 
* `ORDER BY`: returns the data sorted by column specified. Can be sorted in `ASC` (ascending) or `DESC` (descending). 
* `WHERE`: lets you filter on a specific column or value
* `GROUP BY`: lets you aggregate on one or more columns 
* `AVG()`: returns the total average of a particular column 
* `COUNT()`: returns the number of rows in a particular column

In [28]:
-- What is the average price of listings by room type where such listings are available for more than 250 days a year?

# **Q&A**

## Bonus Question: What is the most expensive listing by room type, for listings available more than 100 days a year?

In [30]:
-- What is the most expensive listing by room type, for listings available more than 100 days a year?

In [2]:
from IPython.display import display, HTML

html_code = """
<div id="timer">
    <p>Time: <span id="time">0</span> seconds</p>
    <button onclick="startTimer()">Start Timer</button>
</div>

<style>
    #timer {
        font-family: comic-sans, sans-serif;
        text-align: center;
        margin-top: 20px;
    }
    #timer button {
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
    }
</style>

<script>
    let timer;
    let count = 0;
    
    function displayTime() {
        document.getElementById('time').innerText = count;
        count++;
    }

    function startTimer() {
        if (timer) {
            clearInterval(timer);
        }
        count = 0;
        timer = setInterval(displayTime, 1000);
    }
</script>
"""

display(HTML(html_code))